/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiPage: typeof import('./src/components/AiPage.vue')['default']
    Checkout: typeof import('./src/components/checkout.vue')['default']
    copy: typeof import('./src/components/AiPage copy.vue')['default']
    Customer: typeof import('./src/components/customer.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElText: typeof import('element-plus/es')['ElText']
    Header: typeof import('./src/components/header.vue')['default']
    HomeHeader: typeof import('./src/components/homeHeader.vue')['default']
    Loading: typeof import('./src/components/loading.vue')['default']
    Pagination: typeof import('./src/components/pagination.vue')['default']
    ProductTable: typeof import('./src/components/productTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/sideBar.vue')['default']
    Tabs: typeof import('./src/components/tabs.vue')['default']
  }
}
